"""Temporary forwarding facade; remove after legacy consumers migrate in stage 8."""
from app.compatibility import install_facade
from app.infrastructure.vector import state, qdrant_client_factory, embedding_encoder, chunker, qdrant_vector_store, retrieval_ranker, vector_maintenance

install_facade(__name__, {
    "_get_client": (qdrant_client_factory, "_get_client"),
    "_ensure_collection": (qdrant_client_factory, "_ensure_collection"),
    "EmbeddingUnavailableError": (embedding_encoder, "EmbeddingUnavailableError"),
    "_get_encoder": (embedding_encoder, "_get_encoder"),
    "reset_embedding_initialization": (embedding_encoder, "reset_embedding_initialization"),
    "_embedding_input": (embedding_encoder, "_embedding_input"),
    "embed_text": (embedding_encoder, "embed_text"),
    "embed_texts": (embedding_encoder, "embed_texts"),
    "embedding_signature": (embedding_encoder, "embedding_signature"),
    "_fallback_chunk_offsets": (chunker, "_fallback_chunk_offsets"),
    "_memory_chunk_offsets": (chunker, "_memory_chunk_offsets"),
    "_chunk_point_id": (chunker, "_chunk_point_id"),
    "_write_memory": (qdrant_vector_store, "_write_memory"),
    "save_memory": (qdrant_vector_store, "save_memory"),
    "reconcile_memory": (qdrant_vector_store, "reconcile_memory"),
    "set_memories_status": (qdrant_vector_store, "set_memories_status"),
    "resolve_entity": (qdrant_vector_store, "resolve_entity"),
    "delete_memory_by_session": (qdrant_vector_store, "delete_memory_by_session"),
    "_lexical_overlap": (retrieval_ranker, "_lexical_overlap"),
    "_recency_score": (retrieval_ranker, "_recency_score"),
    "search_memory": (retrieval_ranker, "search_memory"),
    "search_project_memory_candidates": (retrieval_ranker, "search_project_memory_candidates"),
    "get_stats": (vector_maintenance, "get_stats"),
    "warmup_embedding_model": (vector_maintenance, "warmup_embedding_model"),
    "COLLECTION_NAME": (state, "COLLECTION_NAME"),
    "LEGACY_COLLECTION_NAME": (state, "LEGACY_COLLECTION_NAME"),
    "VECTOR_SIZE": (state, "VECTOR_SIZE"),
    "_client_error": (state, "_client_error"),
    "_client_lock": (state, "_client_lock"),
    "_encoder_error": (state, "_encoder_error"),
    "_encoder_failure_count": (state, "_encoder_failure_count"),
    "_encoder_load_attempted": (state, "_encoder_load_attempted"),
    "_encoder_lock": (state, "_encoder_lock"),
    "_encoder_next_retry_at": (state, "_encoder_next_retry_at"),
    "_pending_encoder": (state, "_pending_encoder"),
    "client": (state, "client"),
    "encoder": (state, "encoder"),
    "settings": (state, "settings"),
    "SentenceTransformer": (embedding_encoder, "SentenceTransformer"),
    "time": (embedding_encoder, "time"),
    "uuid": (qdrant_vector_store, "uuid"),
    "_TOKEN_RE": (retrieval_ranker, "_TOKEN_RE"),
})
