"""Low-level completion port; clients are opaque, responses are neutral records."""
from typing import Any, Protocol


class CompletionGateway(Protocol):
    def get_llm_client(self, provider: str | None = None, **kwargs: Any) -> Any: ...
    def get_llm_connection(self, provider: str | None = None) -> tuple[str | None, str | None]: ...
    def create_async_llm_client(self, api_key: str | None, base_url: str | None) -> Any: ...
    def tracked_sync_completion(self, client: Any, **kwargs: Any) -> tuple[Any, str]: ...
    async def tracked_async_completion(self, client: Any, **kwargs: Any) -> tuple[Any, str]: ...
    def memory_completion(self, **kwargs: Any) -> Any: ...
    def serialized_assistant_tool_message(self, message: Any, tool_calls: list[Any]) -> dict: ...
