from datetime import datetime
from typing import Protocol, runtime_checkable


@runtime_checkable
class GraphStore(Protocol):
    def merge_knowledge(self, nodes: list[dict], edges: list[dict], retractions: list[dict] | None = None, source_conversation_id: str | None = None, source_message_id: str | None = None, project_id: str | None = None, project_name: str | None = None, event_id: str | None = None, event_at: datetime | None = None) -> dict: ...
    def search_knowledge(self, keywords: list[str], *, include_historical: bool = False, project_id: str | None = None) -> list[str]: ...
    def get_graph_data(self, limit: int = 300, include_inactive: bool = False) -> dict: ...
    def delete_node(self, entity_key: str) -> dict | None: ...
    def update_node(self, entity_key: str, updates: dict) -> dict | None: ...
    def delete_fact(self, fact_id: str) -> dict | None: ...
    def update_fact(self, fact_id: str, updates: dict) -> dict | None: ...
    def remove_conversation_provenance(self, conversation_id: str, message_ids: list[str] | None = None) -> dict: ...
    def consolidate_memory(self, days_passed: float = 1.0) -> dict: ...
    def get_stats(self) -> dict: ...
