from typing import Any, Protocol


class MemoryTransaction(Protocol):
    def new_message(self, **values: Any) -> Any: ...
    def new_conversation(self, **values: Any) -> Any: ...
    def new_outbox(self, **values: Any) -> Any: ...
    def new_usage(self, **values: Any) -> Any: ...
    def add(self, record: Any) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def refresh(self, record: Any) -> None: ...
    def flush(self) -> None: ...
    def expire_all(self) -> None: ...
    def close(self) -> None: ...
    def begin_turn_conversation(self, session_id: Any) -> Any: ...
    def begin_turn_existing_user(self, session_id: Any, turn_id: Any) -> Any: ...
    def begin_turn_existing_assistant(self, session_id: Any, turn_id: Any) -> Any: ...
    def begin_turn_claimed(self, session_id: Any, turn_id: Any) -> Any: ...
    def begin_turn_update(self, previous_active_turn_id: Any, session_id: Any) -> Any: ...
    def begin_turn_conversation_after_claim(self, session_id: Any) -> Any: ...
    def begin_turn_existing_user_after_claim(self, session_id: Any, turn_id: Any) -> Any: ...
    def begin_turn_existing_assistant_after_claim(self, session_id: Any, turn_id: Any) -> Any: ...
    def cancel_memory_jobs_for_conversation_result(self, session_id: Any) -> Any: ...
    def mark_turn_status_message(self, session_id: Any, turn_id: Any) -> Any: ...
    def mark_turn_status_conversation(self, session_id: Any) -> Any: ...
    def save_interaction_conversation(self, session_id: Any) -> Any: ...
    def save_interaction_msg_user(self, user_message_id: Any) -> Any: ...
    def save_interaction_msg_user_after_claim(self, session_id: Any, turn_id: Any) -> Any: ...
    def save_interaction_msg_ai(self, session_id: Any, turn_id: Any) -> Any: ...
    def save_interaction_memory_job(self, turn_id: Any) -> Any: ...
    def get_session_history_messages(self, limit: Any, session_id: Any) -> Any: ...
    def get_session_summary_row(self, session_id: Any) -> Any: ...
    def claim_memory_job_job(self, job_id: Any) -> Any: ...
    def claim_memory_job_result(self, job_id: Any, legacy_lease_expired_at: Any, now: Any, token: Any) -> Any: ...
    def finish_memory_job_job(self, job_id: Any) -> Any: ...
    def finish_memory_job_changed(self, job_id: Any, lease_token: Any, updates: Any) -> Any: ...
    def finish_memory_job_current(self, job_id: Any) -> Any: ...
    def finish_memory_job_current_after_claim(self, job_id: Any) -> Any: ...
    def get_memory_job_snapshot_job(self, job_id: Any) -> Any: ...
    def update_memory_job_result(self, expected_lease_token: Any, job_id: Any, updates: Any) -> Any: ...
    def update_memory_job_job(self, job_id: Any) -> Any: ...
    def update_memory_job_job_after_claim(self, job_id: Any) -> Any: ...
    def memory_job_is_active_job(self, job_id: Any, lease_token: Any) -> Any: ...
    def memory_job_is_active_result(self, job: Any) -> Any: ...
    def conversation_is_deleted_conversation(self, conversation_id: Any) -> Any: ...
    def process_memory_job_job(self, job_id: Any) -> Any: ...
    def set_source_messages_memory_status_count(self, clean_ids: Any, status: Any) -> Any: ...
    def resolve_project_scope_projects(self) -> Any: ...
    def filter_active_vector_memories_active_ids(self, message_ids: Any) -> Any: ...
    def process_due_memory_jobs_job_ids(self, legacy_lease_expired_at: Any, now: Any, safe_limit: Any) -> Any: ...
    def list_memory_jobs_jobs(self, safe_limit: Any) -> Any: ...
    def retry_memory_job_job(self, job_id: Any) -> Any: ...


class MemoryPersistence(Protocol):
    def open(self) -> MemoryTransaction: ...
    def wrap(self, db: Any) -> MemoryTransaction: ...
