from typing import Any, Protocol


class MemoryWorkflow(Protocol):
    """API-facing workflows backed by bounded application use cases."""
    TurnConflictError: type[Exception]
    def begin_turn(self, *args: Any, **kwargs: Any) -> dict: ...
    def retrieve_context(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_interaction(self, **kwargs: Any) -> dict: ...
    def mark_turn_status(self, *args: Any, **kwargs: Any) -> None: ...
    def process_memory_job(self, *args: Any, **kwargs: Any) -> Any: ...
    def process_conversation_summary(self, *args: Any, **kwargs: Any) -> Any: ...
    def generate_and_save_title(self, *args: Any, **kwargs: Any) -> Any: ...
    def record_internal_error(self, **kwargs: Any) -> Any: ...
    def cancel_memory_jobs_for_conversation(self, session_id: str) -> int: ...
    def list_memory_jobs(self, limit: int = 50) -> list[dict]: ...
    def retry_memory_job(self, job_id: str) -> dict | None: ...
    def set_source_messages_memory_status(self, message_ids: list[str], status: str) -> int: ...


class ConversationHistory(Protocol):
    def get_session_history(self, session_id: str, limit: int = 200) -> list[dict]: ...
    def get_session_summary(self, session_id: str) -> str: ...
