from __future__ import annotations

from typing import Any, Protocol


class ProjectRepository(Protocol):
    def get(self, project_id: str) -> Any: ...
    def list(self) -> list[Any]: ...
    def new(self, **values: Any) -> Any: ...
    def delete(self, project: Any) -> None: ...


class ConversationRepository(Protocol):
    def get(self, session_id: str, *, active_only: bool = False) -> Any: ...
    def list(self) -> list[Any]: ...
    def new(self, **values: Any) -> Any: ...


class MessageRepository(Protocol):
    def history(self, session_id: str) -> list[Any]: ...
    def delete_for_conversation(self, session_id: str) -> None: ...


class MemoryJobRepository(Protocol):
    def get(self, job_id: str) -> Any: ...
    def recent(self, limit: int = 50) -> list[Any]: ...
    def delete_for_conversation(self, session_id: str) -> None: ...


class SettingsRepository(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> Any: ...


class UsageRepository(Protocol):
    def stats(self) -> dict[str, int]: ...


class UnitOfWork(Protocol):
    projects: ProjectRepository
    conversations: ConversationRepository
    messages: MessageRepository
    jobs: MemoryJobRepository
    settings: SettingsRepository
    usage: UsageRepository

    def commit(self) -> None: ...
    def commit_project(self, project: Any) -> None: ...
    def rollback(self) -> None: ...
    def refresh(self, record: Any) -> None: ...
    def close(self) -> None: ...
