from datetime import datetime
from typing import Literal, Protocol, runtime_checkable


@runtime_checkable
class VectorStore(Protocol):
    def save_memory(self, text: str, metadata: dict | None = None, dedup_key: str | None = None, point_id: str | None = None) -> str: ...
    def reconcile_memory(self, text: str, metadata: dict, *, point_id: str) -> bool: ...
    def search_memory(self, query: str, limit: int = 3, *, project_id: str | None = None) -> list[dict]: ...
    def search_project_memory_candidates(self, query: str, limit: int = 12) -> list[dict]: ...
    def set_memories_status(self, message_ids: list[str], *, status: Literal["active", "inactive"], superseded_by: str | None = None, event_at: datetime | None = None) -> int: ...
    def delete_memory_by_session(self, session_id: str) -> None: ...
    def get_stats(self) -> dict: ...
    def embedding_signature(self) -> str: ...
    def warmup_embedding_model(self, *, force_retry: bool = False) -> dict: ...
